name: xpystac-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  # required
  - pystac
  - xarray
  # optional
  - adlfs
  - aiohttp
  - fsspec
  - planetary-computer
  - pystac-client
  - requests
  - rioxarray
  - stackstac
  - zarr
  # testing
  - pytest
  - pytest-cov
  - pytest-vcr
