name: xpystac
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  # required
  - pystac<1.12
  - xarray
  # optional
  - adlfs
  - aiohttp
  - fsspec
  - odc-stac
  - planetary-computer
  - pystac-client
  - requests
  - rioxarray
  - stackstac
  - urllib3
  - zarr<3
  # testing
  - pytest
  - pytest-cov
  - pytest-recording
